App:
  Name: Litrews
  Domain: localhost
  Port: 1323
Log:
  Level: 1 #DEBUG:1, INFO:2, WARN:3, ERROR:4, OFF:5
Database:
  Name: Master
  Dialect: "mysql"
  Addr: "localhost:3306"
  DBName: test
  User: root
  Password:
  Net: tcp
  MaxConnections: 10
  MaxIdleConnections: 5
  ConnectionMaxLifeTime: 180
  Logging: true
